version: '3.8'
services:
  lucky:
    build:
      context: .
      dockerfile: docker/development.dockerfile
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: shards_lib
        target: /app/lib
    ports:
      - 5001:5001

    entrypoint: ["docker/dev_entrypoint.sh"]

volumes:
  shards_lib:
